# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('type_name', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='url_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('add_time', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=10)),
                ('view_time', models.CharField(max_length=20)),
                ('view_count', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
